### ISSUE TITLE
Race Track Diagrams + Verification

### ISSUE THREAD

**Issue by dzenbot** [MultiGP/racesync-ios#21]
Allow getting a list of all UTT track diagrams and GQ (all seasons) directly from within the app. These diagrams would be loaded in the bundle of the application so no network will be needed for accessing them. Besides, the user will have the ability to save these diagrams in their camera roll for ease of use, as well as being able to share to friends/organizers.
Being able to verify GQ track design directly from within the app could also be supported, by either directing to the existing Google Forms, with pre-populated data (user, chapter, etc).

**Tech Requirements:**
If the track verification would be made from within the app using a custom form, then a new API to submit the verification would be required. Else, no backend implementation is needed.

**TODO:**
- [x] Download all UTT diagrams PDFs available at https://www.multigp.com/universal-time-trial-utt/
- [x] Download all GQ diagrams available at https://www.multigp.com/2020-multigp-series-global-qualifier-track-diagram/
- [x] Adapt diagrams to similar style and format, and export in JPG image file
- [x] Add section in Settings, under 'Official Track Layouts'
- [x] Create local JSON with list of track diagrams, divided by UTT and GQ
- [x] Implement an image viewer capable of zooming in/out, panning, exporting diagram to camera roll and share to networks
- [x] Current year's GQ diagrams should include a web link to verification form
